name: Custom Action

on:
  workflow_dispatch:

jobs:
  run_custom_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Custom Action
        uses: ./actions
        with:
          who-to-greet: 'this is a custom action...'
