name: first
on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: |
          env | sort
          date
  job2:
    name: Second Job
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: |
          'Get-ChildItem Env: | Sort-Object Name'
          Get-Date
    
