name: Custom Action

on:
  workflow_dispatch:

jobs:
  run_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Custom Action
        uses: ./actions/action.yml@main
        with:
          who-to-greet: 'this is a custom action...'
