name: Job Output Testing

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: 'This is a fixed message'
      url: ${{ steps.step1.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        run: echo "::set-output name=url::https://azurecorner.com"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.message }}
      - run: echo ${{ needs.job1.outputs.url }}
    
